---
apiVersion: getambassador.io/v3alpha1
kind:  TracingService
metadata:
  name:  tracing
spec:
  service: "zipkin.default.svc.cluster.local:9411"
  driver: zipkin
  config: {}
  custom_tags:  # optional
  - tag: host
    request_header:
      name: ":authority"
      default_value: "unknown"
  - tag: path
    request_header:
      name: ":path"
      default_value: "unknown"
  sampling:
    client: 100
    overall: 100
    random: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          env:
            - name: STORAGE_TYPE
              value: mem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
spec:
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: zipkin
